server:
  port: 8080
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.zxt.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tlias
      username: root
      password: 123456

